In [1]:
import numpy as np
import pandas as pd

In [5]:
A1=np.array([[2,10,-2],[3,2,-2],[8,14,-6]])
print('A1:\n',A1.T)

A1:
 [[ 2  3  8]
 [10  2 14]
 [-2 -2 -6]]


In [6]:
print('rk(A3):\n',np.linalg.matrix_rank(A1.T))

rk(A3):
 2


In [7]:
A2=np.array([[14.3,21.2,8.34, 15.32],[4.3,3.1,0.36, 12.42],[18.6,24.3,8.7, 27.74]])
print('A1:\n',A2.T)

A1:
 [[14.3   4.3  18.6 ]
 [21.2   3.1  24.3 ]
 [ 8.34  0.36  8.7 ]
 [15.32 12.42 27.74]]


In [10]:
A1_inv=np.linalg.inv(A2@A2.T)
A1_inv

LinAlgError: Singular matrix