In [1]:
import numpy as np

In [2]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [3]:
A

array([[11, 10,  8],
       [ 5, 11,  7],
       [10,  5,  6]])

In [4]:
B

array([[ 2, -1,  0],
       [ 0, -1,  3],
       [ 3,  1, -1]])

In [5]:
# Поэлементное умножение
A*B

array([[ 22, -10,   0],
       [  0, -11,  21],
       [ 30,   5,  -6]])

In [6]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ 46 -13  22]
 [ 31  -9  26]
 [ 38  -9   9]]


In [7]:
# Матричное умножение
np.dot(A,B)

array([[ 46, -13,  22],
       [ 31,  -9,  26],
       [ 38,  -9,   9]])

In [8]:
# Матричное умножение
A@B

array([[ 46, -13,  22],
       [ 31,  -9,  26],
       [ 38,  -9,   9]])

In [9]:
# Порядок умножения AB != BA
B@A

array([[17,  9,  9],
       [25,  4, 11],
       [28, 36, 25]])

In [10]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 7  6  8  7  8]
 [ 5  6  5 11  5]
 [10  9 10  5  8]]
B:
 [[ 3 -1]
 [ 2 -2]
 [ 0  1]
 [ 2  1]
 [ 1 -2]]


In [11]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[ 55, -20],
       [ 54, -11],
       [ 66, -29]])

In [12]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [13]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [14]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 1  3  1  2]
 [ 3 -2  3  0]
 [-4  3 -2 -2]
 [-2 -3  0  2]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 1  6  0 -2]
 [ 3 -4  0  0]
 [-4  6  0  2]
 [-2 -6  0 -2]]
DA:
 [[ 1  3  1  2]
 [ 6 -4  6  0]
 [ 0  0  0  0]
 [ 2  3  0 -2]]


In [15]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [16]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [17]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [18]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [19]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [20]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [21]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

In [22]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A@x

array([26, 30])

In [25]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
q = B@A
q[0, 3]

14

In [27]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])
Q = np.array([x, y, z])
Q.T@Q

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [28]:
import pandas as pd
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [29]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [32]:
(Count_DF.values * Price_DF.values) @ com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [34]:
com_st = np.ones(5) - com
com_st

array([0.8, 0.8, 0.7, 0.9, 0.9])

In [36]:
(Count_DF.values * Price_DF.values) @ com_st

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [37]:
# расчет определителя матрицы
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))

-2.9999999999999996


In [38]:
Q = np.matrix('2,0,0;0,1,0;0,0,4')
Q

matrix([[2, 0, 0],
        [0, 1, 0],
        [0, 0, 4]])

In [39]:
np.linalg.det(Q)

7.999999999999998

In [41]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(A)
print(np.linalg.matrix_rank(A))
# ранг равен 2, значит система линейно зависима

[[1 4 7]
 [2 5 8]
 [3 6 9]
 [1 1 1]]
2


In [43]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# ранг равен 32, значит система линейно НЕзависима

3
